/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : Array<string>,
  'articleType' : ArticleType,
  'displayOrder' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'author' : string,
}
export type ArticleType = { 'concept' : null } |
  { 'explained' : null };
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'title' : string,
  'displayOrder' : bigint,
  'link' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
}
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<
    [string, string, Array<string>, ArticleType, string, bigint],
    bigint
  >,
  'createProject' : ActorMethod<
    [string, string, ProjectStatus, Array<string>, string, bigint],
    bigint
  >,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getArticle' : ActorMethod<[bigint], Article>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getArticlesByType' : ActorMethod<[ArticleType], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreatorImageUrl' : ActorMethod<[], string>,
  'getLogoUrl' : ActorMethod<[], string>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isAdminClaimed' : ActorMethod<[], boolean>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'forceResetAdmin' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCreatorImageUrl' : ActorMethod<[string], undefined>,
  'setLogoUrl' : ActorMethod<[string], undefined>,
  'getSiteText' : ActorMethod<[string], string>,
  'getAllSiteTexts' : ActorMethod<[], Array<[string, string]>>,
  'setSiteText' : ActorMethod<[string, string], undefined>,
  'updateArticle' : ActorMethod<
    [bigint, string, string, Array<string>, ArticleType, string, bigint],
    undefined
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, ProjectStatus, Array<string>, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
