/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleType = IDL.Variant({
  'concept' : IDL.Null,
  'explained' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'articleType' : ArticleType,
  'displayOrder' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'author' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ArticleType, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticlesByType' : IDL.Func([ArticleType], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateArticle' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        ArticleType,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleType = IDL.Variant({
    'concept' : IDL.Null,
    'explained' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'articleType' : ArticleType,
    'displayOrder' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'author' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ArticleType, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticlesByType' : IDL.Func(
        [ArticleType],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateArticle' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          ArticleType,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };